[package]
name = "gpu_particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../../libs/app" }
gui = { path = "../../libs/gui" }
rand = "0.8"
num_cpus = "1.13"